const cfg=window.DECOR_CONFIG,sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let categories=[],products=[],projects=[];const fallback='assets/trabajo-walnut.jpg';
const esc=(v='')=>String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
async function ensureAdmin(user){const {data,error}=await sb.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session)return showLogin();if(!await ensureAdmin(session.user)){await sb.auth.signOut();return showLogin('Tu usuario no está autorizado como administrador.')}showAdmin(session.user);await refreshAll()}
function showLogin(msg=''){$('#loginView').classList.remove('hidden');$('#adminView').classList.add('hidden');$('#loginMessage').textContent=msg}
function showAdmin(user){$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#adminEmail').textContent=user.email}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMessage').textContent='Verificando acceso…';const {data,error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)return showLogin(error.message);if(!await ensureAdmin(data.user)){await sb.auth.signOut();return showLogin('Este usuario no está autorizado como administrador.')}showAdmin(data.user);await refreshAll()});
$('#logoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();showLogin()});
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');$('#pageTitle').textContent=b.textContent.trim()}));
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openForm(b.dataset.open)));
$$('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$$('input[type=file]').forEach(input=>input.addEventListener('change',()=>{const f=input.files?.[0],preview=input.closest('form').querySelector('.image-preview');if(f){preview.src=URL.createObjectURL(f);preview.classList.add('show')}}));
function openForm(id,row=null){const d=$('#'+id),f=d.querySelector('form'),preview=f.querySelector('.image-preview');f.reset();f.elements.id.value='';preview.classList.remove('show');preview.removeAttribute('src');if(row){Object.keys(row).forEach(k=>{if(f.elements[k]){if(f.elements[k].type==='checkbox')f.elements[k].checked=!!row[k];else f.elements[k].value=row[k]??''}});if(row.image_url){preview.src=row.image_url;preview.classList.add('show')}}else if(f.elements.active)f.elements.active.checked=true;d.showModal()}
async function refreshAll(){const [c,p,j]=await Promise.all([sb.from('categories').select('*').order('sort_order'),sb.from('products').select('*,categories(name)').order('sort_order'),sb.from('projects').select('*').order('sort_order')]);if(c.error||p.error||j.error){console.error(c.error,p.error,j.error);toast('Error al cargar datos. Revisa la conexión o RLS.');return}categories=c.data||[];products=p.data||[];projects=j.data||[];render()}
function render(){$('#countCategories').textContent=categories.length;$('#countProducts').textContent=products.length;$('#countProjects').textContent=projects.length;const options='<option value="">Selecciona…</option>'+categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#productForm select[name=category_id]').innerHTML=options;$('#productCategoryFilter').innerHTML='<option value="">Todas las categorías</option>'+categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');applyFilters()}
function applyFilters(){const cq=$('#categorySearch').value.toLowerCase(),pq=$('#productSearch').value.toLowerCase(),pf=$('#productCategoryFilter').value,jq=$('#projectSearch').value.toLowerCase();renderCards('#categoryAdminGrid',categories.filter(x=>(x.name+' '+(x.description||'')).toLowerCase().includes(cq)),'category');renderCards('#productAdminGrid',products.filter(x=>(!pf||x.category_id===pf)&&(x.name+' '+(x.description||'')+' '+(x.categories?.name||'')).toLowerCase().includes(pq)),'product');renderCards('#projectAdminGrid',projects.filter(x=>(x.title+' '+(x.description||'')).toLowerCase().includes(jq)),'project')}
['categorySearch','productSearch','productCategoryFilter','projectSearch'].forEach(id=>$('#'+id).addEventListener('input',applyFilters));
function renderCards(sel,rows,type){const grid=$(sel);if(!rows.length){grid.innerHTML='<div class="empty">No hay registros que coincidan.</div>';return}grid.innerHTML=rows.map(r=>`<article class="admin-card ${r.active?'':'inactive'}"><img src="${esc(r.image_url||fallback)}" alt=""><div class="body">${type==='product'?`<small>${esc(r.categories?.name||'Sin categoría')}</small>`:''}<h3>${esc(r.name||r.title)}</h3><p>${esc(r.description||'Sin descripción')}</p><span class="status">${r.active?'Publicado':'Oculto'}</span></div><div class="card-actions"><button data-edit="${type}" data-id="${r.id}">Editar</button><button class="delete" data-delete="${type}" data-id="${r.id}">Eliminar</button></div></article>`).join('');grid.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{const row=(b.dataset.edit==='category'?categories:b.dataset.edit==='product'?products:projects).find(x=>x.id===b.dataset.id);openForm(b.dataset.edit==='category'?'categoryModal':b.dataset.edit==='product'?'productModal':'projectFormModal',row)}));grid.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>removeRow(b.dataset.delete,b.dataset.id)))}
async function upload(file,folder){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('decor-images').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return sb.storage.from('decor-images').getPublicUrl(path).data.publicUrl}
async function saveForm(e,table,folder,label){e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=fd.get('id'),submit=f.querySelector('button[type=submit]'),old=submit.textContent;submit.disabled=true;submit.textContent='Guardando…';try{const image=await upload(fd.get('image')?.size?fd.get('image'):null,folder);const payload={};for(const [k,v] of fd.entries()){if(['id','image'].includes(k))continue;payload[k]=v===''?null:v}payload.active=f.elements.active.checked;payload.sort_order=Number(payload.sort_order||0);if(table==='products'&&payload.price!==null)payload.price=Number(payload.price);if(image)payload.image_url=image;const {error}=id?await sb.from(table).update(payload).eq('id',id):await sb.from(table).insert(payload);if(error)throw error;f.closest('dialog').close();toast(`${label} guardado correctamente`);await refreshAll()}catch(err){console.error(err);toast('Error: '+err.message)}finally{submit.disabled=false;submit.textContent=old}}
$('#categoryForm').addEventListener('submit',e=>saveForm(e,'categories','categories','Categoría'));$('#productForm').addEventListener('submit',e=>saveForm(e,'products','products','Producto'));$('#projectForm').addEventListener('submit',e=>saveForm(e,'projects','projects','Trabajo'));
async function removeRow(type,id){if(!confirm('¿Seguro que deseas eliminar este registro? Esta acción no se puede deshacer.'))return;const table=type==='category'?'categories':type==='product'?'products':'projects';const {error}=await sb.from(table).delete().eq('id',id);if(error)return toast('No se pudo eliminar: '+error.message);toast('Registro eliminado');await refreshAll()}
init();
