(function(){
"use strict";
var cfg=window.DECOR_CONFIG||{},client=null,cats=[],subs=[],products=[],projects=[];
function q(id){return document.getElementById(id)}function esc(s){return String(s||"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]})}
function wa(t){return"https://wa.me/"+(cfg.WHATSAPP_NUMBER||"526563420737")+"?text="+encodeURIComponent(t)}
document.querySelectorAll(".wa").forEach(function(a){a.href=wa("Hola, vi la página de Decor Design y quiero una cotización.");a.target="_blank"});
q("menuBtn").onclick=function(){q("nav").classList.toggle("open")};
var slides=[].slice.call(document.querySelectorAll(".slide")),dots=q("dots"),idx=0;slides.forEach(function(_,i){var s=document.createElement("span");if(i===0)s.className="active";dots.appendChild(s)});var dotEls=[].slice.call(dots.children);function show(i){idx=i;slides.forEach(function(x,n){x.classList.toggle("active",n===i)});dotEls.forEach(function(x,n){x.classList.toggle("active",n===i)})}setInterval(function(){show((idx+1)%slides.length)},5500);
q("closeModal").onclick=function(){q("modal").classList.add("hidden")};q("modal").onclick=function(e){if(e.target===q("modal"))q("modal").classList.add("hidden")};
function money(v){return v==null?"Consultar precio":new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(v))}
async function load(){try{client=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);var r=await Promise.all([client.from("categories").select("*").eq("active",true).order("sort_order"),client.from("subcategories").select("*").eq("active",true).order("sort_order"),client.from("products").select("*").eq("active",true).order("sort_order"),client.from("projects").select("*").eq("active",true).order("sort_order")]);r.forEach(function(x){if(x.error)throw x.error});cats=r[0].data||[];subs=r[1].data||[];products=r[2].data||[];projects=r[3].data||[];render()}catch(e){console.error(e);q("categoryGrid").innerHTML='<p class="loading">No se pudo cargar el catálogo.</p>';q("projectGrid").innerHTML='<p class="loading">No se pudieron cargar los proyectos.</p>'}}
function render(){q("categoryGrid").innerHTML=cats.map(function(c){return'<article class="category" data-id="'+c.id+'"><img src="'+esc(c.image_url||"assets/trabajo-1.jpg")+'"><div><h3>'+esc(c.name)+'</h3><p>'+esc(c.description||"Ver opciones")+'</p></div></article>'}).join("")||'<p class="loading">Sin categorías.</p>';document.querySelectorAll(".category").forEach(function(x){x.onclick=function(){openCategory(x.dataset.id)}});q("projectGrid").innerHTML=projects.map(function(p){return'<article class="project"><img src="'+esc(p.image_url||"assets/trabajo-2.jpg")+'"><div><h3>'+esc(p.title)+'</h3><p>'+esc(p.description||"")+'</p></div></article>'}).join("")||'<p class="loading">Sin proyectos.</p>'}
function openCategory(id){var c=cats.find(function(x){return x.id===id}),ss=subs.filter(function(x){return x.category_id===id});if(ss.length){q("modalTitle").textContent=c.name;q("modalDesc").textContent=c.description||"";q("modalGrid").innerHTML=ss.map(function(s){return'<article class="product" data-sub="'+s.id+'"><img src="'+esc(s.image_url||c.image_url||"assets/trabajo-1.jpg")+'"><div><h3>'+esc(s.name)+'</h3><p>'+esc(s.description||"")+'</p></div></article>'}).join("");document.querySelectorAll("[data-sub]").forEach(function(x){x.onclick=function(){openProducts(c.id,x.dataset.sub)}})}else openProducts(id,null);q("modal").classList.remove("hidden")}
function openProducts(cid,sid){var c=cats.find(function(x){return x.id===cid}),s=sid?subs.find(function(x){return x.id===sid}):null,list=products.filter(function(p){return p.category_id===cid&&(sid?p.subcategory_id===sid:!p.subcategory_id)});q("modalTitle").textContent=s?s.name:c.name;q("modalDesc").textContent=s?s.description||"":c.description||"";q("modalGrid").innerHTML=list.map(function(p){return'<article class="product"><img src="'+esc(p.image_url||c.image_url||"assets/trabajo-1.jpg")+'"><div><h3>'+esc(p.name)+'</h3><p>'+esc(p.description||"")+'</p><p class="price">'+money(p.price)+'</p><a href="'+wa("Hola, quiero información del producto: "+p.name)+'" target="_blank">Cotizar →</a></div></article>'}).join("")||"<p>Sin productos publicados.</p>";q("modal").classList.remove("hidden")}
load();
})();